### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by kopach** [semanser/vim-outdated-plugins#10] opened 2018-11-09 10:36 UTC
Hi. This plugin is awesome. Thank you man. The only issue with it for me is that it slows down (just a little bit) my nvim during startup. So, it would be really cool to enhance that somehow.

I wasn't sure what will be the best way to demonstrate this issue, so I've recorded startup process of my nvim with this plugin and without.

With Plugin:
![with plugin](https://user-images.githubusercontent.com/8749624/48257669-6ed89780-e413-11e8-9a6e-52c7dc7fcba6.gif)

Without Plugin:
![without plugin](https://user-images.githubusercontent.com/8749624/48257673-7435e200-e413-11e8-96fc-90062049f761.gif)

**Please note** how long it takes vim to show startup page after I hit enter

**Comment by semanser** [comment] 2019-06-06 14:00
Hi @kopach, sorry for the delay. 

The issue is fixed in 1.0.2. The plugin runs 4 times faster on my machine now.

**Closed as completed by semanser** 2019-06-06 14:00 UTC
Labels: bug

**Comment by kopach** [comment] 2019-06-06 16:17
Cool, thank you @semanser
